language: node_js
node_js:
  - '5'
  - '4'
services:
  - mongodb
before_install:
  - 'npm install -g npm@latest'
after_success:
  - 'nyc npm test && nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
