language: node_js
node_js:
  - '5'
  - '4'
  - '0.12'
services:
  - mongodb
before_install:
  - 'npm install -g npm@latest'
after_success:
  - '[ -z "$COVERALLS_REPO_TOKEN" ] && nyc npm test && nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
